modLoader="javafml"
loaderVersion="[40,)"
license="MIT"
[[mods]]
modId="bcgunmod"
version="1.18.2"
displayName="MPProject BCGunMod"
logoFile="examplemod.png"
credits="MPProject BlueCitizen Gun Mod"
authors="MPProject"
description='''
MPProject BlueCitizen Gun Mod
'''

[[dependencies.bluecitizen]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.bluecitizen]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2,1.19)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.bluecitizen]]
    modId="cgm"
    mandatory=true
    versionRange="[1.3.3,)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.bluecitizen]]
    modId="framework"
    mandatory=true
    versionRange="[0.4.2,)"
    ordering="NONE"
    side="BOTH"